
### Extension name: REST Client

### Get all notes

GET http://localhost:3000/notes
Content-Type: application/json

### Create a note

POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "Second post",
    "body": "Lorem ipsum random"
}

### Get note by id

GET http://localhost:3000/notes/95ababa6-bad9-4c5d-81d1-c790769072b8
Content-Type: application/json

### Update note

PUT http://localhost:3000/notes/4ddfb44d-202b-4cb3-b178-63994137d810
Content-Type: application/json

{
    "title": "Forth post",
    "body": "Updated placeholder text"
}

### Delete note

DELETE http://localhost:3000/notes/95ababa6-bad9-4c5d-81d1-c790769072b8
Content-Type: application/json

